### ISSUE TITLE
Notification Button disabled

### ISSUE THREAD

**Issue by mahmoud-adel-mahmoud** [SEGUC17/Foobar#23]
1: Severity: ( low )

2:Reported: by Mahmoud

3:Description: When logged in. Navigating to SPS tab. Then opening any profile. Trying to press on notification button but it is disabled.

4: Steps to reproduce the issue: Log in. Then Press on SPS tab. Open any Profile of any service provider. Try pressing on the notification button.

5: Expected result: Notification button should be enabled and open the notification list.

**Comment by markarsanious** [comment]
To view the announcements, view announcements button is there for you in the navbar

**Comment by mahmoud-adel-mahmoud** [comment]
The problem is not with the announcement button it is with the notification button it is disabled.

**Comment by markarsanious** [comment]
yeah i'm telling you , if you want to view the announcements just press its button, the only reason for it is to get you the announcements , it is not there for any other reason believe me :D

**Comment by mahmoud-adel-mahmoud** [comment]
I know that the announcement button is working. But why the notification button that is at the top of the page is not working.

**Comment by markarsanious** [comment]
It is not intended to redirect to the announcement, it is intended to show the total number of announcements on the system and view them from the button
