### ISSUE TITLE
As a system admin i cannot post announcements 

### ISSUE THREAD

**Issue by HatemRamadan** [SEGUC17/Foobar#57]
1: Severity: ( medium )

2:Reported: By Hatem

3:Description: As a system admin there's a tab for posting announcements but it's functioning/working.

4: Steps to reproduce the issue: - log in as a system admin
                                                    - go to Post tab
                                                    - type a title and a content of an announcement
                                                    - the website shows that the announcement was added successfully
                                                    - go to announcements/notifications icon on top right in navigation bar 
                                                       

you will find nothing!    
5: Expected result: the announcement should be added.
![screenshot 86](https://cloud.githubusercontent.com/assets/25323264/25596374/1ec03ad8-2ec9-11e7-85a7-a725db0d1998.png)
![screenshot 87](https://cloud.githubusercontent.com/assets/25323264/25596382/263a2cba-2ec9-11e7-9307-777fbbe37921.png)
![screenshot 90](https://cloud.githubusercontent.com/assets/25323264/25596933/20615de2-2ecc-11e7-8fca-3cbe23be363b.png)

**Comment by markarsanious** [comment]
Man it is working , and  you already posted like million announcements before using it. Seems like the server was overloaded in the last mins before the deadline. That type of issues is not good believe me :D It don't work this way ma bro. 
I will tell you a better idea. try posting empty issues instead to count more issues  ;)

**Comment by HatemRamadan** [comment]
I'm talking about the notifications icon on top right in the navigation bar. Please check it on the last modified version of the website ;)
