### ISSUE TITLE
The website was down for couple minutes

### ISSUE THREAD

**Issue by HatemRamadan** [SEGUC17/Foobar#61]
1: Severity: ( High )

2:Reported: By Hatem

3:Description: The website isn't working. probably is down.

4: Steps to reproduce the issue: just try to load the homepage http://54.77.11.251:8080/

5: Expected result: the homepage
![screenshot 89](https://cloud.githubusercontent.com/assets/25323264/25596682/b6395f4c-2eca-11e7-9438-9114f0de0ee7.png)

**Comment by markarsanious** [comment]
That type of issues can be solved by TEData.

**Comment by HatemRamadan** [comment]
That type of issues can be solved by not modifying the deployed version while testing phase.
