### ISSUE TITLE
accessing all details of any user making announcement

### ISSUE THREAD

**Issue by mmenbawy** [SEGUC17/Foobar#62]
1: Severity: ( high )

2:Reported: By Mostafa

3:Description:    all details of service providers or admins who made announcements including login 
                          details and private info

4: Steps to reproduce the issue: send a get request to http://54.77.11.251:3000/api/announcements/view
                                                   login, announcements, inspect the code, networks, view 

5: Expected result: -
![screenshot 21](https://cloud.githubusercontent.com/assets/25394220/25596963/1957ec62-2edd-11e7-9089-40692615a787.png)

**Comment by amr3mmar** [comment]
We should fix it
